### ISSUE TITLE
Can't locate XML/LibXML/Reader.pm

### ISSUE THREAD

**Issue by daominh6879** [jmcnamara/excel-reader-xlsx#11]
This is the first time I use this zip file. And I have a problem with XML/LibXML/Reader.
Can you give me link to download it?
Thank you very much!

**Comment by jmcnamara** [comment]
Hi @daominh6879,

That error usually means that the module isn't installed.

However, Excel::Reader::XLSX was never release to CPAN and it isn't maintained so I would recommend using Spreadsheet::ParseXLSX instead:

http://search.cpan.org/~doy/Spreadsheet-ParseXLSX/lib/Spreadsheet/ParseXLSX.pm

John
